server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  rabbitmq:
    addresses: xxx
  cloud:
    stream:
      bindings:
        output:
          destination: mail
          group: mail-group

client:
  service:
    url:
      ms-auth: ${SERVICE_URL_MS-AUTH}
