server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

swagger:
  enabled: true

client:
  service:
    url:
      ms-auth: ${SERVICE_URL_MS-AUTH}


  rabbitmq:
    addresses: xxx
  cloud:
    stream:
      bindings:
        output:
          destination: mail
          group: mail-group

