server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG
spring:
  data:
    mongodb:
      uri: xxx

  rabbitmq:
    addresses: xxx
  cloud:
    stream:
      bindings:
        output:
          destination: mail
          group: mail-group

swagger:
  enabled: true

client:
  service:
    url:
      ms-auth: xxx
